apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panda-wiki.fullname" . }}-nats-config
  labels:
    {{- include "panda-wiki.labels" . | nindent 4 }}
data:
  nats.conf: |
    {{- .Values.nats.config | nindent 4 }}
